version: "3.9"
services:

  # api-1
  api-01: &api
    image: jo1opedro/php83-missing-pets-api-2024:v1
    container_name: missing-pets-api-1
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.3.3-bullseye'
    volumes:
       - ./app:/var/www/app
    networks:
      - missing-pets
    env_file:
      - ./app/.env
    environment:
      LARAVEL_OCTANE_PORT: '8000'
    ports:
      - "9000:8000"

  # api-2
  api-02:
    <<: *api
    image: jo1opedro/php83-missing-pets-api-2024:v1
    container_name: missing-pets-api-2
    networks:
      - missing-pets
    env_file:
      - ./app/.env
    environment:
      LARAVEL_OCTANE_PORT: '7000'
    ports:
      - "6000:7000"

  pgsql:
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    #volumes:
      #- 'sail-pgsql:/var/lib/postgresql/data'
      #- './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - missing-pets
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  # Redis
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      volumes:
        - "./app/redis:/data"
      networks:
        - missing-pets
      healthcheck:
        test:
          - CMD
          - redis-cli
          - ping
        retries: 3
        timeout: 5s
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "0.5"
            memory: 200M
          reservations:
            cpus: "0.1"
            memory: 20M
        restart_policy:
          condition: on-failure

  #nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/access.log:/var/log/nginx/access.log
    depends_on:
      - api-01
      - api-02
    ports:
      - "8888:8888"
    networks:
      - missing-pets

networks:
    missing-pets: