version: "3.9"
services:

  # api-1
  api-01: &api
    image: jo1opedro/php83-missing-pets-api-2024:v1
    container_name: missing-pets-api-1
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: "${BUILD_TARGET:-app_dev}"
      args:
        PHP_VERSION: '8.3.3-bullseye'
    volumes:
      - ./app:/var/www/app

  # api-2
  api-02:
    <<: *api
    image: jo1opedro/php83-missing-pets-api-2024:v1
    container_name: missing-pets-api-2
    networks:
      - missing-pets


networks:
  missing-pets: