<?php

namespace Tests;

use Faker\Factory;
use Faker\Generator;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    private Generator $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
        Artisan::call('migrate:fresh');
    }

    public function __get(string $name)
    {
        if($name === 'faker') {
            return $this->faker;
        }
        throw new \Exception('Invalid key requested.');
    }
}
